server:
  port: 8080

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: vietanh2k5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    cache-null-values: false
    redis:
      time-to-live: 30m
  redis:
    host: localhost
    port: 6379
